### ISSUE TITLE
Alert fires twice with two different image URLs when enabling Azure storage

### ISSUE THREAD

**Issue by vhurdugaci-msft** [grafana/alerting#132]
Hello,

I've configured my Grafana instance to upload alert screenshots to Azure:

```
GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_NAME: <redacted>
GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_KEY:  <redacted>
GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_CONTAINER_NAME: <redacted>
GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_SAS_TOKEN_EXPIRATION_DAYS: 14
```

```
grafana.ini:
  external_image_storage:
    provider: azure_blob
unified_alerting.screenshots:
    capture: true
    upload_external_image_storage: true
    max_concurrent_screenshots: 5
imageRenderer:
  enabled: true
  networkPolicy:
    limitIngress: false
```

It all works well and screenshots are uploaded to Blob storage but each alert is sent twice to the webhook contact point. The only difference between the two payloads, is the `imageURL`:

First payload:

```json
{
    "receiver": "Webhook",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "imageURL": "https://<public grafana url>/<image path>"
            ...
        }
    ],
    ...
```

Second payload:

```json
{
    "receiver": "Webhook",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "imageURL": "https://<redacted>.blob.core.windows.net/<rest of the url>"
            ...
        }
    ],
    ...
```

Is this expected behavior? Is there a way to disable the local upload and only get the notification with the azure blob link?
